### ISSUE TITLE
Multi user ids not working in whenTweets

### ISSUE THREAD

**Issue by NumairAwan** [spatie/twitter-streaming-api#40] opened 2022-03-07 23:32 UTC
Hi whenTweets method not working with array of ids. Its working fine with single id but when i use array of ids i am getting nothing.

```
\Spatie\TwitterStreamingApi\PublicStream::create("AAAAAAAAAAAAAAAAAAAAABLGZwEAAA........", "zyiZ4J..............", "DJzgE....................."
        )->whenTweets(['15004825485......','1492193579........'], function(array $tweet) {

            print("Tweet ". $tweet["data"]["text"]) . PHP_EOL;
            
        })->startListening();
```

**Comment by freekmurze** [comment] 2022-03-08 00:24
Duplicate of discussion

**Closed** 2022-03-08 00:24 UTC
